### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jacobwgillespie** [aadnk/AttributeStorage#4]
Hello!  I am working on a pull request for the CommandHelper plugin to add NBT Tag support, and your NbtFactory class (https://github.com/aadnk/AttributeStorage/blob/master/AttributeStorage/src/main/java/com/comphenix/attribute/NbtFactory.java) would be very useful to include in that project.  What license are you releasing your code under?  Would you be okay with that class being included in the pull request (with a comment at the top attributing it to you)?

Thanks!

**Comment by aadnk** [comment]
Oh yeah, I completely forgot ...

I feel it's too short to require any copyleft, so I'll just license it under the [MIT license](http://choosealicense.com/licenses/mit/). :)
